### ISSUE TITLE
Logo gets distorted

### ISSUE THREAD

**Issue by plaihonen** [adiralashiva8/robotframework-metrics#59]
Logo gets distorted due to the both width and height being defined in the style.
`<img src="%s" style="height:18vh!important;width:95%;"/>`

If the width is omitted, then the logo aspect ratio remains correct.
`<img src="%s" style="height:18vh!important;"/>`

This would work fine when logo is provided as a square image. (ex. 512x512 pixels.)

**Comment by fspegni** [comment]
On the other side, in different scenarios, it may be that a short but wide image is "cropped" with your suggestion. Perhaps setting the `max-height` and `max-width` should solve the original problem of not showing a distorted image, no matter its height/width ratio, e.g.

``
                      <img src="%s" style="max-height:18vh;max-width:95%%;"/>
``

**Comment by adiralashiva8** [comment]
Fixed as part of https://github.com/adiralashiva8/robotframework-metrics/pull/65 pull request

**Comment by adiralashiva8** [comment]
Seems this issue not fixed, Modifying sidebar will fix this issue

**Comment by adiralashiva8** [comment]
Modified sidebar which fixes image distorting in this commit https://github.com/adiralashiva8/robotframework-metrics/commit/3cb7a5f156789c0e7f784d105a13c2f71142e712
